# Generated by Django 5.0.6 on 2024-06-29 02:51

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_marca_producto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),  # Usar datetime.date.today para fecha actual
            preserve_default=False,
        ),
    ]
